language: java

jdk:
  - openjdk11

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V


script: mvn clean package jacoco:report

after_success: mvn clean test jacoco:report coveralls:report

